### ISSUE TITLE
вёрстка пуш-месседжей

### ISSUE THREAD

**Issue by TorinAsakura** [AtlantisUnited/AtlassianTelegramBot#1]
Пример имплементации можешь смело брать с нашего телеграм бота. 1 в 1 можешь брать.

**Comment by TFK70** [comment]
![image](https://user-images.githubusercontent.com/62806448/196505713-39b397f9-95a2-464c-8f00-10d7e570b461.png)

Плюс добавил поддержку вебхука для комментов:

![image](https://user-images.githubusercontent.com/62806448/196505772-d6fea0ed-0b5f-4b4e-859e-3a0920d859f4.png)
